run:
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases -e
all:
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases
verbose:
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases -e -v
all-verbose:
	bash setup.sh
	python3 TestCenter-master/testcenter.py -s soln -t test-cases -v
